export const SET_DELIVERED = "SET_DELIVERED";
export const SET_UNDELIVERED = "SET_UNDELIVERED";
export const SET_MODAL_UPDATER = "SET_MODAL_UPDATER";
export const SET_USER_SESSION = "SET_USER_SESSION";
