export const HOME_PAGE_PATH = "request-tracker";
export const LOGIN_PAGE_URL = "/login";
export const PROJECTS_ENDPOINT = "https://igodev.mskcc.org/request-tracker/api/projects";
export const FEEDBACK_ENDPOINT = "http://localhost:4000/api/feedback";
export const HOME = "/request-tracker";
export const HOST = "https://igodev.mskcc.org";
// export const HOME_PAGE_PATH = "";
// export const PROJECTS_ENDPOINT = "http://localhost:4000/api/projects";
// export const LOGIN_PAGE_URL = "http://localhost:3000/";
