export const MOCK_REQUEST = {
    "status":1,
    "message":"success",
    "data":{
    "request":{
        "summary":{
            "total":12,
                "RecentDeliveryDate":1600293934040,
                "stagesComplete":true,
                "isIgoComplete":true,
                "completed":12,
                "failed":0
        },
        "metaData":{
            "ProjectName":"RBP CRISPRa screen",
                "sourceProjects":[],
                "QcAccessEmails":"streidd@mskcc.org",
                "LaboratoryHead":"LAB_HEAD",
                "RequestName":"NextSeq-Other",
                "TATFromInProcessing":"01 days 05 hours and 11 min.",
                "Investigator":"INVESTIGATOR",
                "ProjectManager":"",
                "ReceivedDate":1600041757768,
                "TATFromReceiving":"01 days 19 hours and 00 min.",
                "GroupLeader":"GRPOUP_LEADER",
                "LabHeadEmail":"streidd@mskcc.org",
                "DataAccessEmails":"streidd@mskcc.org"
        },
        "requestId":"10958_C",
            "bankedSampleId":"IGO-018252",
            "stages":[
            {
                "stage":"Submitted",
                "completedSamples":12,
                "totalSamples":12,
                "startTime":null,
                "updateTime":null,
                "complete":true,
                "failedSamples":0
            },
            {
                "stage":"Sequencing",
                "completedSamples":12,
                "totalSamples":12,
                "startTime":1600041571555,
                "updateTime":1600196612576,
                "complete":true,
                "failedSamples":0
            },
            {
                "stage":"Data QC",
                "completedSamples":12,
                "totalSamples":12,
                "startTime":1600041475240,
                "updateTime":1600041587131,
                "complete":true,
                "failedSamples":0
            }
        ],
            "samples":[
            {
                "sampleId":8143753,
                "root":{
                    "recordId":8143753,
                    "children":[
                        {
                            "recordId":8143802,
                            "children":[
                                {
                                    "recordId":8165652,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_1",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859501,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165653,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_2",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859515,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165654,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_3",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859529,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165655,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_4",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859543,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165674,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_5",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600184174483,
                                        "updateTime":1600184174569,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"In Process - Illumina Sequencing"
                                    }
                                }
                            ],
                            "recordName":"Pool-10958_C-Tube1",
                            "attributes":{
                                "stage":"Sequencing",
                                "totalSamples":0,
                                "startTime":1600041571555,
                                "updateTime":1600196612576,
                                "failed":false,
                                "sourceSampleId":"",
                                "complete":true,
                                "status":"Completed - Illumina Sequencing"
                            }
                        }
                    ],
                    "recordName":"10958_C_1",
                    "attributes":{
                        "stage":"Data QC",
                        "totalSamples":0,
                        "startTime":1600041475240,
                        "updateTime":1600041579957,
                        "failed":false,
                        "sourceSampleId":"",
                        "complete":true,
                        "status":"Processing Completed"
                    }
                },
                "stages":[
                    {
                        "stage":"Sequencing",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041571555,
                        "updateTime":1600196612576,
                        "complete":true,
                        "failedSamples":0
                    },
                    {
                        "stage":"Data QC",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041475240,
                        "updateTime":1600041579957,
                        "complete":true,
                        "failedSamples":0
                    }
                ],
                "status":"Complete"
            },
            {
                "sampleId":8143757,
                "root":{
                    "recordId":8143757,
                    "children":[
                        {
                            "recordId":8143802,
                            "children":[
                                {
                                    "recordId":8165652,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_1",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859501,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165653,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_2",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859515,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165654,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_3",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859529,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165655,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_4",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859543,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165674,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_5",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600184174483,
                                        "updateTime":1600184174569,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"In Process - Illumina Sequencing"
                                    }
                                }
                            ],
                            "recordName":"Pool-10958_C-Tube1",
                            "attributes":{
                                "stage":"Sequencing",
                                "totalSamples":0,
                                "startTime":1600041571555,
                                "updateTime":1600196612576,
                                "failed":false,
                                "sourceSampleId":"",
                                "complete":true,
                                "status":"Completed - Illumina Sequencing"
                            }
                        }
                    ],
                    "recordName":"10958_C_2",
                    "attributes":{
                        "stage":"Data QC",
                        "totalSamples":0,
                        "startTime":1600041475314,
                        "updateTime":1600041576863,
                        "failed":false,
                        "sourceSampleId":"",
                        "complete":true,
                        "status":"Processing Completed"
                    }
                },
                "stages":[
                    {
                        "stage":"Sequencing",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041571555,
                        "updateTime":1600196612576,
                        "complete":true,
                        "failedSamples":0
                    },
                    {
                        "stage":"Data QC",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041475314,
                        "updateTime":1600041576863,
                        "complete":true,
                        "failedSamples":0
                    }
                ],
                "status":"Complete"
            },
            {
                "sampleId":8143761,
                "root":{
                    "recordId":8143761,
                    "children":[
                        {
                            "recordId":8143802,
                            "children":[
                                {
                                    "recordId":8165652,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_1",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859501,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165653,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_2",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859515,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165654,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_3",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859529,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165655,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_4",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859543,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165674,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_5",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600184174483,
                                        "updateTime":1600184174569,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"In Process - Illumina Sequencing"
                                    }
                                }
                            ],
                            "recordName":"Pool-10958_C-Tube1",
                            "attributes":{
                                "stage":"Sequencing",
                                "totalSamples":0,
                                "startTime":1600041571555,
                                "updateTime":1600196612576,
                                "failed":false,
                                "sourceSampleId":"",
                                "complete":true,
                                "status":"Completed - Illumina Sequencing"
                            }
                        }
                    ],
                    "recordName":"10958_C_3",
                    "attributes":{
                        "stage":"Data QC",
                        "totalSamples":0,
                        "startTime":1600041475387,
                        "updateTime":1600041585099,
                        "failed":false,
                        "sourceSampleId":"",
                        "complete":true,
                        "status":"Processing Completed"
                    }
                },
                "stages":[
                    {
                        "stage":"Sequencing",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041571555,
                        "updateTime":1600196612576,
                        "complete":true,
                        "failedSamples":0
                    },
                    {
                        "stage":"Data QC",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041475387,
                        "updateTime":1600041585099,
                        "complete":true,
                        "failedSamples":0
                    }
                ],
                "status":"Complete"
            },
            {
                "sampleId":8143765,
                "root":{
                    "recordId":8143765,
                    "children":[
                        {
                            "recordId":8143802,
                            "children":[
                                {
                                    "recordId":8165652,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_1",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859501,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165653,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_2",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859515,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165654,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_3",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859529,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165655,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_4",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859543,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165674,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_5",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600184174483,
                                        "updateTime":1600184174569,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"In Process - Illumina Sequencing"
                                    }
                                }
                            ],
                            "recordName":"Pool-10958_C-Tube1",
                            "attributes":{
                                "stage":"Sequencing",
                                "totalSamples":0,
                                "startTime":1600041571555,
                                "updateTime":1600196612576,
                                "failed":false,
                                "sourceSampleId":"",
                                "complete":true,
                                "status":"Completed - Illumina Sequencing"
                            }
                        }
                    ],
                    "recordName":"10958_C_4",
                    "attributes":{
                        "stage":"Data QC",
                        "totalSamples":0,
                        "startTime":1600041475461,
                        "updateTime":1600041581989,
                        "failed":false,
                        "sourceSampleId":"",
                        "complete":true,
                        "status":"Processing Completed"
                    }
                },
                "stages":[
                    {
                        "stage":"Sequencing",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041571555,
                        "updateTime":1600196612576,
                        "complete":true,
                        "failedSamples":0
                    },
                    {
                        "stage":"Data QC",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041475461,
                        "updateTime":1600041581989,
                        "complete":true,
                        "failedSamples":0
                    }
                ],
                "status":"Complete"
            },
            {
                "sampleId":8143769,
                "root":{
                    "recordId":8143769,
                    "children":[
                        {
                            "recordId":8143802,
                            "children":[
                                {
                                    "recordId":8165652,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_1",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859501,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165653,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_2",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859515,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165654,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_3",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859529,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165655,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_4",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859543,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165674,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_5",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600184174483,
                                        "updateTime":1600184174569,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"In Process - Illumina Sequencing"
                                    }
                                }
                            ],
                            "recordName":"Pool-10958_C-Tube1",
                            "attributes":{
                                "stage":"Sequencing",
                                "totalSamples":0,
                                "startTime":1600041571555,
                                "updateTime":1600196612576,
                                "failed":false,
                                "sourceSampleId":"",
                                "complete":true,
                                "status":"Completed - Illumina Sequencing"
                            }
                        }
                    ],
                    "recordName":"10958_C_5",
                    "attributes":{
                        "stage":"Data QC",
                        "totalSamples":0,
                        "startTime":1600041475533,
                        "updateTime":1600041578927,
                        "failed":false,
                        "sourceSampleId":"",
                        "complete":true,
                        "status":"Processing Completed"
                    }
                },
                "stages":[
                    {
                        "stage":"Sequencing",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041571555,
                        "updateTime":1600196612576,
                        "complete":true,
                        "failedSamples":0
                    },
                    {
                        "stage":"Data QC",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041475533,
                        "updateTime":1600041578927,
                        "complete":true,
                        "failedSamples":0
                    }
                ],
                "status":"Complete"
            },
            {
                "sampleId":8143773,
                "root":{
                    "recordId":8143773,
                    "children":[
                        {
                            "recordId":8143802,
                            "children":[
                                {
                                    "recordId":8165652,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_1",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859501,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165653,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_2",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859515,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165654,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_3",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859529,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165655,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_4",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859543,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165674,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_5",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600184174483,
                                        "updateTime":1600184174569,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"In Process - Illumina Sequencing"
                                    }
                                }
                            ],
                            "recordName":"Pool-10958_C-Tube1",
                            "attributes":{
                                "stage":"Sequencing",
                                "totalSamples":0,
                                "startTime":1600041571555,
                                "updateTime":1600196612576,
                                "failed":false,
                                "sourceSampleId":"",
                                "complete":true,
                                "status":"Completed - Illumina Sequencing"
                            }
                        }
                    ],
                    "recordName":"10958_C_6",
                    "attributes":{
                        "stage":"Data QC",
                        "totalSamples":0,
                        "startTime":1600041475617,
                        "updateTime":1600041575751,
                        "failed":false,
                        "sourceSampleId":"",
                        "complete":true,
                        "status":"Processing Completed"
                    }
                },
                "stages":[
                    {
                        "stage":"Sequencing",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041571555,
                        "updateTime":1600196612576,
                        "complete":true,
                        "failedSamples":0
                    },
                    {
                        "stage":"Data QC",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041475617,
                        "updateTime":1600041575751,
                        "complete":true,
                        "failedSamples":0
                    }
                ],
                "status":"Complete"
            },
            {
                "sampleId":8143777,
                "root":{
                    "recordId":8143777,
                    "children":[
                        {
                            "recordId":8143802,
                            "children":[
                                {
                                    "recordId":8165652,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_1",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859501,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165653,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_2",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859515,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165654,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_3",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859529,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165655,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_4",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859543,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165674,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_5",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600184174483,
                                        "updateTime":1600184174569,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"In Process - Illumina Sequencing"
                                    }
                                }
                            ],
                            "recordName":"Pool-10958_C-Tube1",
                            "attributes":{
                                "stage":"Sequencing",
                                "totalSamples":0,
                                "startTime":1600041571555,
                                "updateTime":1600196612576,
                                "failed":false,
                                "sourceSampleId":"",
                                "complete":true,
                                "status":"Completed - Illumina Sequencing"
                            }
                        }
                    ],
                    "recordName":"10958_C_7",
                    "attributes":{
                        "stage":"Data QC",
                        "totalSamples":0,
                        "startTime":1600041475690,
                        "updateTime":1600041587131,
                        "failed":false,
                        "sourceSampleId":"",
                        "complete":true,
                        "status":"Processing Completed"
                    }
                },
                "stages":[
                    {
                        "stage":"Sequencing",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041571555,
                        "updateTime":1600196612576,
                        "complete":true,
                        "failedSamples":0
                    },
                    {
                        "stage":"Data QC",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041475690,
                        "updateTime":1600041587131,
                        "complete":true,
                        "failedSamples":0
                    }
                ],
                "status":"Complete"
            },
            {
                "sampleId":8143781,
                "root":{
                    "recordId":8143781,
                    "children":[
                        {
                            "recordId":8143802,
                            "children":[
                                {
                                    "recordId":8165652,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_1",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859501,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165653,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_2",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859515,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165654,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_3",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859529,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165655,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_4",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859543,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165674,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_5",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600184174483,
                                        "updateTime":1600184174569,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"In Process - Illumina Sequencing"
                                    }
                                }
                            ],
                            "recordName":"Pool-10958_C-Tube1",
                            "attributes":{
                                "stage":"Sequencing",
                                "totalSamples":0,
                                "startTime":1600041571555,
                                "updateTime":1600196612576,
                                "failed":false,
                                "sourceSampleId":"",
                                "complete":true,
                                "status":"Completed - Illumina Sequencing"
                            }
                        }
                    ],
                    "recordName":"10958_C_8",
                    "attributes":{
                        "stage":"Data QC",
                        "totalSamples":0,
                        "startTime":1600041475773,
                        "updateTime":1600041584068,
                        "failed":false,
                        "sourceSampleId":"",
                        "complete":true,
                        "status":"Processing Completed"
                    }
                },
                "stages":[
                    {
                        "stage":"Sequencing",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041571555,
                        "updateTime":1600196612576,
                        "complete":true,
                        "failedSamples":0
                    },
                    {
                        "stage":"Data QC",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041475773,
                        "updateTime":1600041584068,
                        "complete":true,
                        "failedSamples":0
                    }
                ],
                "status":"Complete"
            },
            {
                "sampleId":8143785,
                "root":{
                    "recordId":8143785,
                    "children":[
                        {
                            "recordId":8143802,
                            "children":[
                                {
                                    "recordId":8165652,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_1",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859501,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165653,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_2",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859515,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165654,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_3",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859529,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165655,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_4",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859543,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165674,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_5",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600184174483,
                                        "updateTime":1600184174569,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"In Process - Illumina Sequencing"
                                    }
                                }
                            ],
                            "recordName":"Pool-10958_C-Tube1",
                            "attributes":{
                                "stage":"Sequencing",
                                "totalSamples":0,
                                "startTime":1600041571555,
                                "updateTime":1600196612576,
                                "failed":false,
                                "sourceSampleId":"",
                                "complete":true,
                                "status":"Completed - Illumina Sequencing"
                            }
                        }
                    ],
                    "recordName":"10958_C_9",
                    "attributes":{
                        "stage":"Data QC",
                        "totalSamples":0,
                        "startTime":1600041475856,
                        "updateTime":1600041580980,
                        "failed":false,
                        "sourceSampleId":"",
                        "complete":true,
                        "status":"Processing Completed"
                    }
                },
                "stages":[
                    {
                        "stage":"Sequencing",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041571555,
                        "updateTime":1600196612576,
                        "complete":true,
                        "failedSamples":0
                    },
                    {
                        "stage":"Data QC",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041475856,
                        "updateTime":1600041580980,
                        "complete":true,
                        "failedSamples":0
                    }
                ],
                "status":"Complete"
            },
            {
                "sampleId":8143789,
                "root":{
                    "recordId":8143789,
                    "children":[
                        {
                            "recordId":8143802,
                            "children":[
                                {
                                    "recordId":8165652,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_1",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859501,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165653,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_2",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859515,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165654,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_3",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859529,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165655,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_4",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859543,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165674,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_5",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600184174483,
                                        "updateTime":1600184174569,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"In Process - Illumina Sequencing"
                                    }
                                }
                            ],
                            "recordName":"Pool-10958_C-Tube1",
                            "attributes":{
                                "stage":"Sequencing",
                                "totalSamples":0,
                                "startTime":1600041571555,
                                "updateTime":1600196612576,
                                "failed":false,
                                "sourceSampleId":"",
                                "complete":true,
                                "status":"Completed - Illumina Sequencing"
                            }
                        }
                    ],
                    "recordName":"10958_C_10",
                    "attributes":{
                        "stage":"Data QC",
                        "totalSamples":0,
                        "startTime":1600041475929,
                        "updateTime":1600041577871,
                        "failed":false,
                        "sourceSampleId":"",
                        "complete":true,
                        "status":"Processing Completed"
                    }
                },
                "stages":[
                    {
                        "stage":"Sequencing",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041571555,
                        "updateTime":1600196612576,
                        "complete":true,
                        "failedSamples":0
                    },
                    {
                        "stage":"Data QC",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041475929,
                        "updateTime":1600041577871,
                        "complete":true,
                        "failedSamples":0
                    }
                ],
                "status":"Complete"
            },
            {
                "sampleId":8143793,
                "root":{
                    "recordId":8143793,
                    "children":[
                        {
                            "recordId":8143802,
                            "children":[
                                {
                                    "recordId":8165652,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_1",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859501,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165653,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_2",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859515,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165654,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_3",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859529,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165655,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_4",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859543,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165674,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_5",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600184174483,
                                        "updateTime":1600184174569,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"In Process - Illumina Sequencing"
                                    }
                                }
                            ],
                            "recordName":"Pool-10958_C-Tube1",
                            "attributes":{
                                "stage":"Sequencing",
                                "totalSamples":0,
                                "startTime":1600041571555,
                                "updateTime":1600196612576,
                                "failed":false,
                                "sourceSampleId":"",
                                "complete":true,
                                "status":"Completed - Illumina Sequencing"
                            }
                        }
                    ],
                    "recordName":"10958_C_11",
                    "attributes":{
                        "stage":"Data QC",
                        "totalSamples":0,
                        "startTime":1600041476003,
                        "updateTime":1600041586116,
                        "failed":false,
                        "sourceSampleId":"",
                        "complete":true,
                        "status":"Processing Completed"
                    }
                },
                "stages":[
                    {
                        "stage":"Sequencing",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041571555,
                        "updateTime":1600196612576,
                        "complete":true,
                        "failedSamples":0
                    },
                    {
                        "stage":"Data QC",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041476003,
                        "updateTime":1600041586116,
                        "complete":true,
                        "failedSamples":0
                    }
                ],
                "status":"Complete"
            },
            {
                "sampleId":8143797,
                "root":{
                    "recordId":8143797,
                    "children":[
                        {
                            "recordId":8143802,
                            "children":[
                                {
                                    "recordId":8165652,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_1",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859501,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165653,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_2",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859515,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165654,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_3",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859529,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165655,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_4",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600183859543,
                                        "updateTime":1600196612576,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"Completed - Illumina Sequencing"
                                    }
                                },
                                {
                                    "recordId":8165674,
                                    "children":[

                                    ],
                                    "recordName":"Pool-10958_C-Tube1_5",
                                    "attributes":{
                                        "stage":"Sequencing",
                                        "totalSamples":0,
                                        "startTime":1600184174483,
                                        "updateTime":1600184174569,
                                        "failed":false,
                                        "sourceSampleId":"",
                                        "complete":true,
                                        "status":"In Process - Illumina Sequencing"
                                    }
                                }
                            ],
                            "recordName":"Pool-10958_C-Tube1",
                            "attributes":{
                                "stage":"Sequencing",
                                "totalSamples":0,
                                "startTime":1600041571555,
                                "updateTime":1600196612576,
                                "failed":false,
                                "sourceSampleId":"",
                                "complete":true,
                                "status":"Completed - Illumina Sequencing"
                            }
                        }
                    ],
                    "recordName":"10958_C_12",
                    "attributes":{
                        "stage":"Data QC",
                        "totalSamples":0,
                        "startTime":1600041476087,
                        "updateTime":1600041583023,
                        "failed":false,
                        "sourceSampleId":"",
                        "complete":true,
                        "status":"Processing Completed"
                    }
                },
                "stages":[
                    {
                        "stage":"Sequencing",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041571555,
                        "updateTime":1600196612576,
                        "complete":true,
                        "failedSamples":0
                    },
                    {
                        "stage":"Data QC",
                        "completedSamples":0,
                        "totalSamples":1,
                        "startTime":1600041476087,
                        "updateTime":1600041583023,
                        "complete":true,
                        "failedSamples":0
                    }
                ],
                "status":"Complete"
            }
        ]
    },
    "requestId":"10958_C",
        "serviceId":"IGO-018252"
}
}
